server:
  port: 8084
spring:
  application:
    name: user-service # 微服务名称
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${jh.db.host}:3307/hm-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${jh.db.pw}
  cloud:
    nacos:
      server-addr: 114.116.225.208:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.jh: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 商城用户管理接口文档
    description: "商城用户管理接口文档"
    email: jh790074213@163.com
    concat: jh
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.jh.user.controller
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
feign:
  okhttp:
    enabled: true # 开启OKHttp功能