server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
jh:
  db:
    database: hm-user
  swagger:
    title: 商城用户管理接口文档
    desc: "商城用户管理接口文档"
    package: com.jh.user.controller
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m